---
title: "Testes de Aderência"
author: "Juliana Magalhães Rosa"
date: "10/26/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#Indicando diretório
setwd("~/Me2/atividade_4")
```

```{r}
#Carregando bibliotecas
library(dgof)
library(EnvStats)
library(dplyr)
library(ggplot2)
```

```{r}
#Definindo média e desvio padrão
set.seed(12081961)
media <- sample(100:200, 1)
dp <- media*0.1
```

```{r}
#Gerando mil amostras de tamanho 15
amostras <- list()
set.seed(14031968)
for (i in 1:1000){
  amostras <- append(amostras, rnorm(15, 116, 11.6))
}
amostras <- as.numeric(amostras)
```

```{r}
#Teste de Kolmogorov-Smirnov para 1 amostra
k_est <- list()
x <- 1
while (x<=14986){
  k_est <- append(k_est, ks.test(amostras[x:(x+14)], "pnorm", 116, 11.6)[1])
  x <- x+15
}
k_est <- as.numeric(k_est)
```

```{r}
#Teste de Lilliefors
lillie_est <- list()
y <- 1
while (y<=14986){
  lillie_est <- append(lillie_est, gofTest(amostras[y:(y+14)], test="lillie")[6])
  y <- y+15
}
lillie_est <- as.numeric(lillie_est)
```

```{r}
#Criando dataframe com estatísticas do teste
ests <- list(k_est, lillie_est)
ests <- as.data.frame(ests, 
                    col.names=c("k_est", "lillie_est"))
```

```{r}
#Separando k_est em intervalos de classes
k1=1+3.3*log10(1000)
k1
h1=(max(ests$k_est)-min(ests$k_est))/k1
h1
ests$k_est.cut = cut(ests$k_est, breaks=c(0.08, 0.116, 0.152, 0.188, 0.224, 0.26, 0.296, 0.332, 0.368,
                                          0.404, 0.44, 0.476))
```

```{r}
#Tabela k_est
with(ests, table(k_est.cut))
```

```{r}
#Histograma k_est
ggplot(ests, aes(k_est))+
  geom_histogram(binwidth=0.036, fill="blue4")+
  theme_light()+
  ggtitle("Histograma da Estatística do Teste de Kolmogorov para Normalidade")+
  xlab("Estatística de Kolmogorov")+
  ylab("Frequência")
```

```{r}
#Medidas descritivas k_est
ests%>%
  summarize(media=mean(k_est), q1=quantile(k_est, 0.25),
            mediana=median(k_est), q3=quantile(k_est, 0.75), q4=max(k_est),
            amplitude=max(k_est)-min(k_est), iiq=IQR(k_est), variancia=var(k_est),
            dp=sd(k_est), cv=sd(k_est)/mean(k_est), Ap=3*(media-mediana)/dp,
            Aq=((q3-mediana)-(mediana-q1))/iiq,
            k=(q3-q1)/(2*(quantile(k_est, 0.9)-quantile(k_est, 0.1))))
```

```{r}
#Boxplot k_est
ggplot(ests, aes(k_est))+
  geom_boxplot(outlier.shape=8)+
  coord_flip()+
  theme_light()+
  theme(axis.ticks.x=element_blank(), axis.text.x=element_blank())+
  ggtitle("Box Plot da Estatística do Teste de Kolmogorov para Normalidade")+
  xlab("Estatística de Kolmogorov")
```

```{r}
#Calculando quantis k_est
ests%>%
  summarize(quantil_80=quantile(k_est, 0.8), quantil_85=quantile(k_est, 0.85),
            quantil_90=quantile(k_est, 0.9), quantil_95=quantile(k_est, 0.95),
            quantil_975=quantile(k_est, 0.975), quantil_99=quantile(k_est, 0.99))
```

```{r}
#Separando lillie_est em intervalos de classes
k1
h2=(max(ests$lillie_est)-min(ests$lillie_est))/k1
h2
ests$lillie_est.cut = cut(ests$lillie_est, breaks=c(0.069, 0.09, 0.111, 0.132, 0.153, 0.174, 0.195, 0.216, 0.237,
                                          0.258, 0.279, 0.3))
```

```{r}
#Tabela lillie_est
with(ests, table(lillie_est.cut))
```

```{r}
#Histograma lillie_est
ggplot(ests, aes(lillie_est))+
  geom_histogram(binwidth=0.021, fill="blue4")+
  theme_light()+
  ggtitle("Histograma da Estatística do Teste de Lilliefors para Normalidade")+
  xlab("Estatística de Lilliefors")+
  ylab("Frequência")
```

```{r}
#Medidas descritivas lillie_est
ests%>%
  summarize(media=mean(lillie_est), q1=quantile(lillie_est, 0.25),
            mediana=median(lillie_est), q3=quantile(lillie_est, 0.75), q4=max(lillie_est),
            amplitude=max(lillie_est)-min(lillie_est), iiq=IQR(lillie_est), variancia=var(lillie_est),
            dp=sd(lillie_est), cv=sd(lillie_est)/mean(lillie_est), Ap=3*(media-mediana)/dp,
            Aq=((q3-mediana)-(mediana-q1))/iiq,
            k=(q3-q1)/(2*(quantile(lillie_est, 0.9)-quantile(lillie_est, 0.1))))
```

```{r}
#Boxplot lillie_est
ggplot(ests, aes(lillie_est))+
  geom_boxplot(outlier.shape=8)+
  coord_flip()+
  theme_light()+
  theme(axis.ticks.x=element_blank(), axis.text.x=element_blank())+
  ggtitle("Box Plot da Estatística do Teste de Lilliefors para Normalidade")+
  xlab("Estatística de Lilliefors")
```

```{r}
#Calculando quantis lillie_est
ests%>%
  summarize(quantil_80=quantile(lillie_est, 0.8), quantil_85=quantile(lillie_est, 0.85),
            quantil_90=quantile(lillie_est, 0.9), quantil_95=quantile(lillie_est, 0.95),
            quantil_975=quantile(lillie_est, 0.975), quantil_99=quantile(lillie_est, 0.99))
```

```{r}
#Selecionando 5 amostras
set.seed(0397)
amostra_1 <- amostras[sample(1000, 15)]

set.seed(0955)
amostra_2 <- amostras[sample(1000, 15)]

set.seed(114)
amostra_3 <- amostras[sample(1000, 15)]

set.seed(7174)
amostra_4 <- amostras[sample(1000, 15)]

set.seed(5202)
amostra_5 <- amostras[sample(1000, 15)]
```

```{r}
#Testes de Shapiro-Wilk
gofTest(amostra_1, test="sw")
gofTest(amostra_2, test="sw")
gofTest(amostra_3, test="sw")
gofTest(amostra_4, test="sw")
gofTest(amostra_5, test="sw")
```

```{r}
#Testes de Anderson-Darling
gofTest(amostra_1, test="ad")
gofTest(amostra_2, test="ad")
gofTest(amostra_3, test="ad")
gofTest(amostra_4, test="ad")
gofTest(amostra_5, test="ad")
```
